# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Zachary Melancon"
  avatar: avatar.png
  gravatar: "zmelan01@gmail.com" # Email MD5 has
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Examples of Web Applications Developed by Me.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "zmelan01@gmail.com"
  github: "melanconz"
  google_plus: "+zacharymelancon"
  linkedin:  "https://www.linkedin.com/in/zacharymelancon"
  stack_exchange: "https://stackexchange.com/users/6992574/zachary-melancon"

  # Scripts
  google_analytics: "UA-77537277-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
